# -*- coding:utf-8 -*-

SYSTEM_PROMPT = """
You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
"""

PROMPT = """
Role: You are an expert in image/video light and shadow analysis, good at analyzing light and shadow from multiple angles.

Tasks: Analyze the input image/video, provide corresponding classification results for the following multiple categories, and return them in the specified output format.

1. **Direction of Light**：
  Task 1: Analyze the image and classify the light source direction as front light, side light, back light, top light, bottom light, or split light. Identify the angle of the light source relative to the subject, and describe its effect on shadow formation.

  - **Front Light:**
      Definition: The light source is positioned directly in front of the subject, illuminating it head-on.
  - **Side Light:**
      Definition: The light source is positioned at a 90-degree or 45-degree angle to the subject, coming from the side.
  - **Back Light:**
      Definition: The light source is located behind the subject, directed towards the camera.
  - **Top Light:**
      Definition: The light source is positioned directly above the subject, casting light downwards.
  - **Bottom Light:**
      Definition: The light source is positioned below the subject, casting light upwards.
  - **Split Light:**
      Definition: The light source illuminates one side of the subject while leaving the other side in shadow, effectively splitting the lighting.
  - **Ambient Light Without Clear Direction:**
      Definition: Ambient light is a non-directional light source that fills the environment uniformly, often coming from multiple sources.

2. **Light Source Type**：
  Task 2: Analyze the image and classify the light source type as either Natural Light, Artificial Light, or Rendering Light.

  - **Natural Light:**
      Definition: Natural light refers to any illumination that occurs in nature without human intervention. It can vary significantly based on:
        - Time of Day: The quality and color of natural light change from sunrise to sunset, with softer, warmer tones during the golden hour and harsh, bright light at noon.
        - Weather Conditions: Cloud coverage, rain, or fog can diffuse and soften natural light, while clear skies provide strong direct sunlight.
        - Geographical Location: The angle of the sun varies with latitude, affecting the intensity and quality of light in different regions.
  - **Artificial Light:**
      Definition: Artificial light is generated by human-made sources, used to illuminate spaces for various purposes, from functional lighting to artistic effects. It encompasses:
        - Types of Light Sources: Examples include incandescent bulbs, fluorescent lights, LED fixtures, and neon signs, each with distinct color temperatures and usage characteristics.
        - Lighting Purposes: Functional lighting (e.g., in offices or kitchens) versus decorative lighting (e.g., in theaters or art installations) can create different ambiance and visual effects.
        - Environmental Context: The setting where the artificial light is applied, such as indoor spaces, outdoor streets, or special events, influences its impact and perception.
  - **Rendering Light:**
      Definition: Rendering light refers to digital light sources used in graphic design, 3D modeling, and computer-generated imagery (CGI). Key aspects include:
        - Scene Types: In video games, dynamic lighting techniques simulate real-world light conditions, while animated cartoons may use stylized lighting for emotional effect.
        - Technical Features: Rendering can entail complex algorithms (like ray tracing) to replicate natural and artificial lighting behaviors, including shadows, reflections, and color interactions within virtual environments.
        - Use Cases: Depending on the context—whether it is an animated film, a game environment, or a product visualization—rendering light serves to enhance storytelling and visual engagement in unique ways.

3. **Light Intensity**：
  Task 3: Analyze the image/video to assess the light intensity present. Classify the light intensity into three categories: Glare (>1000 lumens), Moderate (200–1000 lumens), and Dim (<200 lumens). Special attention should be given to situations where bright light sources may create a glaring effect even in otherwise dim environments.

  - **Glare:**
      Definition: This category represents extremely bright lighting conditions that can cause discomfort or hinder visibility. Light in this range can be overwhelming and may create a harsh visual experience, particularly when bright light is encountered in dimly lit environments. Can lead to visual fatigue, strain, and discomfort for viewers. Often creates strong glare on surfaces, obscuring details and making it difficult to see.
  - **Moderate:**
      Definition: This category denotes balanced lighting that is generally comfortable and suitable for most activities. It provides adequate visibility without causing strain or discomfort. Allows for clear visibility and adequate detail recognition, enhancing visual comfort for prolonged viewing or activities.
  - **Dim:**
      Definition: This category indicates low light conditions that can create a cozy or intimate atmosphere but may hinder visibility and detail recognition. Common in evening settings, low-light environments, or areas with minimal lighting. However, even in dim settings, the presence of exceptionally bright light can be perceived as glare, impacting overall visibility.

4. **Color Temperature**：
  Task 4: Analyze the image/video to assess the color temperature present. Classify the color temperature into three categories: Cool Tone, Neutral, and Warm Tone. 

  - **Cool Tone:**
      Definition: Cool tone color temperatures typically range from 5000K to 10000K and are characterized by bluish hues. This tone is often associated with daylight or overcast conditions. It's important to carefully evaluate the overall context and atmosphere of the video, ensuring that the characterization as a cool tone is appropriate based on the predominant lighting and color interaction in the scene.
  - **Neutral:**
      Definition: Neutral color temperatures typically range from 4000K to 5000K and represent a balanced lighting condition that avoids extreme warmth or coolness. In cases where the lighting appears balanced without strong inclinations toward blue or yellow hues, it should be categorized as neutral.
  - **Warm Tone:**
      Definition: Warm tone color temperatures typically range from 2000K to 4000K and are associated with reddish or yellowish hues. This tone is often linked to sunrise, sunset, or cozy indoor lighting. A careful assessment of the scene’s overall ambiance is essential; ensure that the classification as a warm tone reflects a significant presence of warmth in color temperature and is not made lightly.

5. **Light Changes in Time**：
  Task 5: Analyze the video to assess light changes over time. Classify the light changes into two main categories: Static Light and Dynamic Light. For Dynamic Light, further categorize it into two subtypes: Intensity Gradient and Moving Light Source.

    - **Static Light:**
        Definition: Static light refers to illumination that remains constant in intensity and direction over time. There is no noticeable change in brightness or the light source’s position throughout the video frames. When analyzing the video, focus exclusively on frame-to-frame variations in light; do not make assumptions based on the content of the images.
    - **Dynamic Light(Intensity Changing Light):**
        Definition: Dynamic light refers to illumination that changes over time in intensity. This subtype involves gradual changes in light intensity, such as transitions from dawn to daylight or shifts from bright to dim lighting within a scene. Ensure that these changes are assessed solely through temporal variations observed across video frames.
    - **Dynamic Light(Moving Light Source):**
        Definition: Dynamic light refers to illumination that changes over time in direction. This subtype involves the physical movement of the light source itself, such as the motion of a car’s headlights across the scene or stage lighting that is panned or tilted. Observe these movements as they occur in the video frames without inferring context based on visual content.

6. **Optical Phenomena**：
  Task 6: Analyze the image/video with a focus on the specific scene to assess the optical phenomena present. Pay close attention to scenarios involving glass, water surfaces, mirrors, and fog. Classify the phenomena into the following categories: Transmission (Glass), Refraction/Reflection (Water Surface, Mirror), Refraction/Reflection (Mirror), Scattering (Fog Effect), and None.

  - **Transmission (Glass):**
      Definition: Transmission refers to the passage of light through transparent materials, such as glass. In scenarios involving windows or glass surfaces, observe how light interacts with glass, paying special attention to various lighting conditions. Note any absorption and scattering that may occur alongside the light's path through the glass.
  - **Refraction/Reflection (Water Surface, Mirror):**
      Definition: Refraction and reflection occur when light encounters different materials, which can lead to changes in its direction. Refraction involves bending light as it passes through mediums like water, while reflection involves bouncing light off surfaces like mirrors. In environments with water or mirrors, analyze how these surfaces modify the appearance and behavior of light and how they impact the overall scene.
  - **Scattering (Fog Effect):**
      Definition: Scattering occurs when light interacts with small particles in the atmosphere or other mediums, causing the light to change direction and spread out. This effect is commonly observed in fog, mist, or smoke. In scenes featuring fog, closely examine how scattering affects visibility and light diffusion, contributing to the ambiance of the scene.
  - **None:**
      Definition: No optical phenomena are present in the image/video. Ensure that properties of light behavior are thoroughly evaluated, paying special attention to the scene characteristics, even if phenomena appear minimal.

**Guidelines:**

1. **Accuracy:** Assign each tag to the most appropriate category and subcategory.
2. **Multiple Tags:** If an action fits multiple categories, assign all relevant tags.
3. **Comprehensiveness:** Capture all detectable dynamic attributes without omissions.
4. **JSON Validity:** Ensure the output JSON is correctly formatted and adheres to the specified structure.

**Example Output:**

```json
{
    "Direction of Light": "Front Light",
    "Light Source Type": "Artificial Light",
    "Light Intensity": "Moderate",
    "Color Temperature": "Cool Tone"
    "Light Changes in Time": "Dynamic Light (Intensity Changing Light)",
    "Optical Phenomena": "Transmission (Glass)"
}
"""